#!/usr/bin/bash

miweb="$1"

if [ -z $miweb ]; then
  echo "miweb <nombre>"
  exit
fi

if [ -d $miweb ]; then
  echo "ERROR el fichero ya existe"
  exit
fi

mkdir -p $miweb/css $miweb/img $miweb/js $miweb/html;
touch $miweb/index.html $miweb/css/main.css $miweb/js/main.js
cat <<EOF >> $miweb/index.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="author" content="David Soliman Escobar" />
  <title>$1</title>
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/main.css">
</head>
<body>

  <h1>Vamos con todo! $1</h1>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src='js/main.js'></script>
</body>
</html>
EOF
cd $miweb
git init
wget https://necolas.github.io/normalize.css/8.0.1/normalize.css
wget https://raw.githubusercontent.com/SolimanHub/scraping_css/main/diccionario_css
mv normalize.css css/
mv diccionario_css css/
> k
cat <<EOF >> k
#!/usr/bin/bash
nvim index.html css/main.css js/main.js css/diccionario_css 
EOF
chmod +x k

cat <<EOF >> css/main.css

/*a - e*/ 
body {
  blackground-color: rgba(220, 220, 220, 0.3);
  margin: 0;
  padding: 0;
}

/*f - j*/
/*k - o*/
/*p - t*/
/*u - z*/

@media only screen and (min-width: 1440px) {
/*a - e*/ 
/*f - j*/
/*k - o*/
/*p - t*/
/*u - z*/
}

@media only screen and (min-width: 961px) and (max-width: 1439px) {
/*a - e*/ 
/*f - j*/
/*k - o*/
/*p - t*/
/*u - z*/
}

@media only screen and (min-width: 640px) and (max-width: 960px) {
/*a - e*/ 
/*f - j*/
/*k - o*/
/*p - t*/
/*u - z*/
}

@media only screen and (max-width: 639px) {
/*a - e*/ 
/*f - j*/
/*k - o*/
/*p - t*/
/*u - z*/
}

EOF

cat <<EOF >> js/main.js
$(document).ready(function() {
  $(".class").click(function(){
    //
  });
  document.getElementById('id').style.display = 'none/block';
}

function name(){
//
}
EOF
