#!/usr/bin/bash

miweb="$1"

if [ -z $miweb ]; then
  echo "miweb <nombre>"
  exit
fi

if [ -d $miweb ]; then
  echo "ERROR el fichero ya existe"
  exit
fi

mkdir -p $miweb/css $miweb/js $miweb/html;
mkdir -p $miweb/recursos/img $miweb/recursos/js $miweb/recursos/css $miweb/recursos/icon;
touch $miweb/index.html $miweb/css/css_main.css $miweb/js/js_main.js
touch $miweb/.gitignore

cat <<EOF >> $miweb/index.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="author" content="David Soliman Escobar" />
  <title>$1</title>
  <link rel="stylesheet" href="recursos/css/normalize.css">
  <link rel="stylesheet" href="css/css_main.css">
</head>
<body>

  <div class="container">
    <h1>$1</h1>
  </div> <!-- end container -->

  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
  <script src='js/js_main.js'></script>
</body>
</html>
EOF
cd $miweb
git init

cat <<EOF >> .gitignore
.gitignore
EOF

wget https://necolas.github.io/normalize.css/8.0.1/normalize.css
#wget https://raw.githubusercontent.com/SolimanHub/scraping_css/main/diccionario_css
mv normalize.css recursos/css/
#mv diccionario_css css/
touch k
cat <<EOF >> k
#!/usr/bin/bash
nvim -p index.html css/css_main.css js/js_main.js 
EOF
chmod +x k

cat <<EOF >> css/css_main.css

body {
  background-color: rgba(220, 220, 220, 0.3);
  margin: 0;
  padding: 0;
}

.container {
  width: 99%;
  display: grid;
  grid-template-columns: repeat( 12, 1fr );
  grid-auto-rows: minmax( 100px auto );
}

@media only screen and (max-width: 320px) {
/*...*/ 
}

@media only screen and (min-width: 321px) and (max-width: 512px) {
/*...*/ 
}

@media only screen and (min-width: 513px) and (max-width: 640px) {
/*...*/ 
}

@media only screen and (min-width: 641px) and (max-width: 720px) {
/*...*/ 
}

@media only screen and (min-width: 721px) and (max-width: 800px) {
/*...*/ 
}

@media only screen and (min-width: 801px) and (max-width: 850px) {
/*...*/ 
}

@media only screen and (min-width: 851px) and (max-width: 1024px) {
/*...*/ 
}

@media only screen and (min-width: 1025px) and (max-width: 1152px) {
/*...*/ 
}

@media only screen and (min-width: 1153px) and (max-width: 1280px) {
/*...*/ 
}

@media only screen and (min-width: 1281px) and (max-width: 1366px) {
/*...*/ 
}

@media only screen and (min-width: 1367px) and (max-width: 1440px) {
/*...*/ 
}

@media only screen and (min-width: 1441px) and (max-width: 1920px) {
/*...*/ 
}

@media only screen and (min-width: 1921px) and (max-width: 2048px) {
/*...*/ 
}

@media only screen and (min-width: 2049px) and (max-width: 2560px) {
/*...*/ 
}

EOF

#cat <<EOF >> js/js_main.js
#$(document).ready(function() {
#  $(".class").click(function(){
#    //
#  });
#  document.getElementById('id').style.display = 'none/block';
#}
#
#function name(){
#//
#}
#EOF
